### ISSUE TITLE
Macros to simplify management of references to the events and metrics indices

### ISSUE THREAD

**Issue by jdubby** [delphix/SplunkApp#1]
Using macros instead of hard-coded index names in searches allows for a single place to edit the index name, rather than needing to update every search in every dashboard.
* Create macro `delphix_events_index` and set the value to `index=delphix_events`
* Create macro `delphix_metrics_index` and set the value to `index=delphix_metrics`
* Update all searches to replace hard-coded index names with macro references
* Update documentation to demonstrate how to change index names in the macros to match their index names

**Comment by prashks** [comment]
Cool, this is first step towards being able to customize this app and hence a perfect PR # 1 👍
